### ISSUE TITLE
Results: update fields and format outputs of interview data

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare_jupyter_sync#14]
This Issue should be closed when there is consistency between Interview data reported in tables and figures.  

## Feedback
The initial phase of interviews has Table 1 with Stage of Career and count of hydrologists. Can we expand this or create a Table 2 that provides the results from the interviews that translate to Figure 1 (divergent network)?  

### Ideas/Options
Present tables to report the values used in figures. Stage of career in Table 1 is not directly consistent with X-axis of Figure 1. 
- [ ] Add column to a Table to relate count of interviewees with experience (table column and Figure 1 X-axis) 
- [ ] Add a text list of workflows (in documentation text or listed in word-wrapped row/column) 
- [ ] Add count of workflows per experience level (table column). 

### Consensus-building questions
Do we like the description of the method/results "Exploratory User Workflow Interviews"  ?

- [ ] Yes. Naming consistent in documentation of presentation and final report. 

- [ ] No.  Different name preferred.  Consistent throughout deliverables.

**Comment by kylecombes** [comment]
Hi Christina, thanks for the feedback. If you're going to create an issue for something in the [final report](https://docs.google.com/document/d/1sZYOdTaVRwnKQfVeLUUOGoSpAzTOcwTLsYEsqYkG9uk/edit), would you mind linking to it in the doc? That's where we're keeping track of our todos regarding the paper, and we're generally considering GitHub issues to be TODOs for future developers. Thanks!

**Comment by kylecombes** [comment]
Hi Christina,
Unfortunately, I don't think we have the data to create what you're after. We could potentially generate part of what you're after if we had access to our notes from AGU, but unfortunately all of us seem to have left those at Olin.
