### ISSUE TITLE
Documentation: Acknowledgements

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare_jupyter_sync#17]
**Short: **
We acknowledge funding from the U.S. National Science Foundation for OAC-1664061 (Bandaragoda,Tarboton, Black) and CUAHSI EAR-1338606 (Pollak, Castronova).

**Long:**
We acknowledge funding from the U.S. National Science Foundation for OAC-1664061 (Bandaragoda,Tarboton, Black) and CUAHSI EAR-1338606 (Pollak, Castronova). These development grants support the Consortium of Universities for the Advancement of Hydrologic Science, Inc (CUAHSI), University of Washington, Utah State University, and Olin College.  Other contributors to the development of the HydroShare platform (http://www.hydroshare.org) include Brigham Young University, Tufts University, University of Virginia, University of Washington, National Center for Atmospheric Research (NCAR), Purdue University, University of Texas at Austin, We acknowledge early contributions from HydroShare developers supported by (ACI 1148453 2012 - 2018). Any opinions, findings, and conclusions or recommendations expressed in this material are those of the authors and do not necessarily reflect the views of the National Science Foundation.  We recommend users of this tool use this form to provide them information on acknowledging CUAHSI resources.
 
**Partner grant details include:**
USU HydroShare 1 2012-2017, ACI 1148453
RENCI HydroShare 1 2012-2017, ACI 1148090  
USU HydroShare 2 2017-2021, OAC-1664061
UNC Chapel Hill, RENCI HydroShare 2 2017-2021, OAC-1664018
University of Illinois HydroShare 2 2017-2021, OAC-1664119
CUAHSI Cooperative agreement 2014-2020, EAR 1338606
USU Hurricane Harvey and Irma RAPID 2017-2018, OAC-1761763

**Comment by kylecombes** [comment]
Hi Christina, thanks for the feedback. If you're going to create an issue for something in the final report, would you mind linking to it in [the doc](https://docs.google.com/document/d/1sZYOdTaVRwnKQfVeLUUOGoSpAzTOcwTLsYEsqYkG9uk/edit)? That's where we're keeping track of our todos regarding the paper, and we're generally considering GitHub issues to be TODOs for future developers. Thanks!
Also, we have added this to our report.
