### ISSUE TITLE
Recommendations: Visioning a Sync-Enabled Steamlining of workflows

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare_jupyter_sync#33]
@goodalljl @zhiyuli @hydroshare/jupyterhub  - could we develop a workflow demo that circles a ‘typical’ workflow for a researcher who develops on their desktop (familiar with Github push/pull with teammates).  

In a research environment designed to enable multiple diverging pathways, consider these two starting points.  **3-click  Happy Family Introduction** and **Building Atomic Habits for Deep Nutrition Introduction**

## **3-click  Happy Family Introduction**

Three components to the Happy Family User Experience: a) there are a lot of ingredients in the pot, b) the outcome is pleasing enough for everyone, c) users are not interested in the details of why it's so delicious - they are hungry and grateful just to have it work.  User persona Alex needs this workflow or he's probably going to get so frustrated he will eventually leave academia for a tech job. 

Use Case: A Link to HydroShare resource is emailed to a colleague or student or posted on Twitter.  

* Click (1) on link and launch demonstration Notebook,  Interact, Be Inspired AND geo-educated

* Click (2) to save new interesting results and write a message to the HydroShare data owners. 
 - "I cited your work after testing this notebook, here is a link to my article that builds on your work."   
-  "I used your data and it is just what I needed to test my hypothesis, do you want to collaborate on a proposal?"  
- "My students learned so much from your research by interacting with the model and data. I'll send you the evaluations for your tenure package. "

* Click (3) on Sync to save selected files back to HydroShare with message to resource owners (who get email or Github notification).   

Other Optional existing workflows similar to existing workflow enabled by Binder and set up by HydroShare resource owners: 

Option B-  Click to HydroShare.com/alphanumericawesomeness.  Click on Sync Badge/Button to open Sync interface that is customized to this research publication with any specific instructions.   Requires Resource landing page UI development for a button.  Add extended metadata that populates the button with a hyperlink to Binder info.  Instructions to research publication users on building Welcome notebooks that are not confusing to sharing their data with new users. 

Option C (exists; needs doc):   Click to HydroShare.com/alphanumericawesomeness.  Right click on Notebook  launches to WebApp.  Needs Instructions to research publication users on how to setup the metadata and links to enable and maintain this feature. 

Option D (exists; needs doc):   Click to ydroShare.com/alphanumericawesomeness. Open With web app.  The HS resource owner controls options on what the user sees next - a selected interactive Notebook of choice or server directory view - and which server is used.

## **Building Atomic Habits for Deep Nutrition Introduction**

Three components to the Deep Nutrition User Experience: a) there are a lot of ingredients in the pot, b) there is time, funding and a long term investment in learning Github, python, scripting, FAIR standards, sustainable research software releases, reproducible modeling, etc.  c) everyone needs to test and analyze all the data with access to all the CI details - they signed up for a marathon and committed to keep making it work.  Janet gets this. 

Steps: 
1. User builds model/saves observation data/does homework on their Desktop (imagine a researcher student with installation instructions from professor or open source software community, or government employee with existing workflows that depend on or are formally limited to their PC).  
2. Move scripts and testing Notebook from a PC using Sync to HydroShare
3. Set up resource landing page to enable **Happy Family Introductions** to their research users.  For example, Notebook launches to CyberGIS-Water (other JHserver with bigger compute access like XSEDE).
4.  After testing on XSEDE, research software, notebooks and requirements are packaging and finalizing on Github.    From XSEDE, users uses Sync to publish modeled products on HydroShare for DOI.  
5. User gets feedback when users launch Sync Binder for workshops and classroom use. 

What development steps are needed?  Button on JH server. Messaging service integrated.  Installation instructions. User testing.  Sustainable maintenance.  Anything else?

**Comment by aaraney** [comment]
I like these user stories, potential feature additions, and general suggestions. For future readers of this issue, the context of this issue was for the original students working on this project (see #76).
